// goctl rpc protoc ./pb/billSvr.proto --proto_path=./pbserver/  --proto_path=./pb/  --go_out=./pbgo --go_opt=paths=source_relative  --go-grpc_out=./pbgo  --go-grpc_opt=paths=source_relative --zrpc_out=./app/billsvr/src
// protoc --proto_path=./pb --go_out=./pbgo --go_opt=paths=source_relative ./pb/billSvr.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: billSvr.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HistoricalRegistrations int32 `protobuf:"varint,1,opt,name=historical_registrations,json=historicalRegistrations,proto3" json:"historical_registrations,omitempty"` // 历史注册用户总数
	RegisteredUsers         int32 `protobuf:"varint,2,opt,name=registered_users,json=registeredUsers,proto3" json:"registered_users,omitempty"`                         // 当日注册用户数
	ActiveUsers             int32 `protobuf:"varint,3,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`                                     // 活跃用户数
	PaidUsers               int32 `protobuf:"varint,4,opt,name=paid_users,json=paidUsers,proto3" json:"paid_users,omitempty"`                                           // 付费用户数
	PaymentOccurrences      int32 `protobuf:"varint,5,opt,name=payment_occurrences,json=paymentOccurrences,proto3" json:"payment_occurrences,omitempty"`                // 付费人次
	PaymentTotal            int32 `protobuf:"varint,6,opt,name=payment_total,json=paymentTotal,proto3" json:"payment_total,omitempty"`                                  // 付费额度
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{0}
}

func (x *UserStats) GetHistoricalRegistrations() int32 {
	if x != nil {
		return x.HistoricalRegistrations
	}
	return 0
}

func (x *UserStats) GetRegisteredUsers() int32 {
	if x != nil {
		return x.RegisteredUsers
	}
	return 0
}

func (x *UserStats) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *UserStats) GetPaidUsers() int32 {
	if x != nil {
		return x.PaidUsers
	}
	return 0
}

func (x *UserStats) GetPaymentOccurrences() int32 {
	if x != nil {
		return x.PaymentOccurrences
	}
	return 0
}

func (x *UserStats) GetPaymentTotal() int32 {
	if x != nil {
		return x.PaymentTotal
	}
	return 0
}

type UserStatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HistoricalRegistrations int32 `protobuf:"varint,1,opt,name=historical_registrations,json=historicalRegistrations,proto3" json:"historical_registrations,omitempty"` // 历史注册用户总数
	RegisteredUsers         int32 `protobuf:"varint,2,opt,name=registered_users,json=registeredUsers,proto3" json:"registered_users,omitempty"`                         // 当日注册用户数
	ActiveUsers             int32 `protobuf:"varint,3,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`                                     // 活跃用户数
	PaidUsers               int32 `protobuf:"varint,4,opt,name=paid_users,json=paidUsers,proto3" json:"paid_users,omitempty"`                                           // 付费用户数
	PaymentOccurrences      int32 `protobuf:"varint,5,opt,name=payment_occurrences,json=paymentOccurrences,proto3" json:"payment_occurrences,omitempty"`                // 付费人次
	PaymentTotal            int32 `protobuf:"varint,6,opt,name=payment_total,json=paymentTotal,proto3" json:"payment_total,omitempty"`                                  // 付费额度
}

func (x *UserStatsReq) Reset() {
	*x = UserStatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsReq) ProtoMessage() {}

func (x *UserStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsReq.ProtoReflect.Descriptor instead.
func (*UserStatsReq) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{1}
}

func (x *UserStatsReq) GetHistoricalRegistrations() int32 {
	if x != nil {
		return x.HistoricalRegistrations
	}
	return 0
}

func (x *UserStatsReq) GetRegisteredUsers() int32 {
	if x != nil {
		return x.RegisteredUsers
	}
	return 0
}

func (x *UserStatsReq) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *UserStatsReq) GetPaidUsers() int32 {
	if x != nil {
		return x.PaidUsers
	}
	return 0
}

func (x *UserStatsReq) GetPaymentOccurrences() int32 {
	if x != nil {
		return x.PaymentOccurrences
	}
	return 0
}

func (x *UserStatsReq) GetPaymentTotal() int32 {
	if x != nil {
		return x.PaymentTotal
	}
	return 0
}

type UserStatsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HistoricalRegistrations int32 `protobuf:"varint,1,opt,name=historical_registrations,json=historicalRegistrations,proto3" json:"historical_registrations,omitempty"` // 历史注册用户总数
	RegisteredUsers         int32 `protobuf:"varint,2,opt,name=registered_users,json=registeredUsers,proto3" json:"registered_users,omitempty"`                         // 当日注册用户数
	ActiveUsers             int32 `protobuf:"varint,3,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`                                     // 活跃用户数
	PaidUsers               int32 `protobuf:"varint,4,opt,name=paid_users,json=paidUsers,proto3" json:"paid_users,omitempty"`                                           // 付费用户数
	PaymentOccurrences      int32 `protobuf:"varint,5,opt,name=payment_occurrences,json=paymentOccurrences,proto3" json:"payment_occurrences,omitempty"`                // 付费人次
	PaymentTotal            int32 `protobuf:"varint,6,opt,name=payment_total,json=paymentTotal,proto3" json:"payment_total,omitempty"`                                  // 付费额度
}

func (x *UserStatsRsp) Reset() {
	*x = UserStatsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStatsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsRsp) ProtoMessage() {}

func (x *UserStatsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsRsp.ProtoReflect.Descriptor instead.
func (*UserStatsRsp) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{2}
}

func (x *UserStatsRsp) GetHistoricalRegistrations() int32 {
	if x != nil {
		return x.HistoricalRegistrations
	}
	return 0
}

func (x *UserStatsRsp) GetRegisteredUsers() int32 {
	if x != nil {
		return x.RegisteredUsers
	}
	return 0
}

func (x *UserStatsRsp) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *UserStatsRsp) GetPaidUsers() int32 {
	if x != nil {
		return x.PaidUsers
	}
	return 0
}

func (x *UserStatsRsp) GetPaymentOccurrences() int32 {
	if x != nil {
		return x.PaymentOccurrences
	}
	return 0
}

func (x *UserStatsRsp) GetPaymentTotal() int32 {
	if x != nil {
		return x.PaymentTotal
	}
	return 0
}

type RetainedUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *RetainedUsers) Reset() {
	*x = RetainedUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetainedUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainedUsers) ProtoMessage() {}

func (x *RetainedUsers) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainedUsers.ProtoReflect.Descriptor instead.
func (*RetainedUsers) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{3}
}

func (x *RetainedUsers) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type RetainedUsersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetainedUsersReq) Reset() {
	*x = RetainedUsersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetainedUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainedUsersReq) ProtoMessage() {}

func (x *RetainedUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainedUsersReq.ProtoReflect.Descriptor instead.
func (*RetainedUsersReq) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{4}
}

type RetainedUsersRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetainedUsersRsp) Reset() {
	*x = RetainedUsersRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetainedUsersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainedUsersRsp) ProtoMessage() {}

func (x *RetainedUsersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainedUsersRsp.ProtoReflect.Descriptor instead.
func (*RetainedUsersRsp) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{5}
}

type UserChurnStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *UserChurnStats) Reset() {
	*x = UserChurnStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChurnStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChurnStats) ProtoMessage() {}

func (x *UserChurnStats) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChurnStats.ProtoReflect.Descriptor instead.
func (*UserChurnStats) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{6}
}

func (x *UserChurnStats) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type UserChurnStatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserChurnStatsReq) Reset() {
	*x = UserChurnStatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChurnStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChurnStatsReq) ProtoMessage() {}

func (x *UserChurnStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChurnStatsReq.ProtoReflect.Descriptor instead.
func (*UserChurnStatsReq) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{7}
}

type UserChurnStatsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserChurnStatsRsp) Reset() {
	*x = UserChurnStatsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChurnStatsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChurnStatsRsp) ProtoMessage() {}

func (x *UserChurnStatsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChurnStatsRsp.ProtoReflect.Descriptor instead.
func (*UserChurnStatsRsp) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{8}
}

type SceneOccupationStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *SceneOccupationStats) Reset() {
	*x = SceneOccupationStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneOccupationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneOccupationStats) ProtoMessage() {}

func (x *SceneOccupationStats) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneOccupationStats.ProtoReflect.Descriptor instead.
func (*SceneOccupationStats) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{9}
}

func (x *SceneOccupationStats) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type SceneOccupationStatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SceneOccupationStatsReq) Reset() {
	*x = SceneOccupationStatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneOccupationStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneOccupationStatsReq) ProtoMessage() {}

func (x *SceneOccupationStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneOccupationStatsReq.ProtoReflect.Descriptor instead.
func (*SceneOccupationStatsReq) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{10}
}

type SceneOccupationStatsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SceneOccupationStatsRsp) Reset() {
	*x = SceneOccupationStatsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billSvr_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneOccupationStatsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneOccupationStatsRsp) ProtoMessage() {}

func (x *SceneOccupationStatsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_billSvr_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneOccupationStatsRsp.ProtoReflect.Descriptor instead.
func (*SceneOccupationStatsRsp) Descriptor() ([]byte, []int) {
	return file_billSvr_proto_rawDescGZIP(), []int{11}
}

var File_billSvr_proto protoreflect.FileDescriptor

var file_billSvr_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x69, 0x6c, 0x6c, 0x53, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x89, 0x02, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x39, 0x0a, 0x18, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63,
	0x61, 0x6c, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63,
	0x61, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x29, 0x0a, 0x10, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x61, 0x69, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x70, 0x61, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x13,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x4f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x23, 0x0a,
	0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0x8c, 0x02, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x39, 0x0a, 0x18, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61,
	0x6c, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61,
	0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29,
	0x0a, 0x10, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x61, 0x69, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x70, 0x61, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x13, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x4f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0x8c, 0x02, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x73, 0x70, 0x12, 0x39, 0x0a, 0x18, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c,
	0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29, 0x0a,
	0x10, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x61, 0x69, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x70, 0x61, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x13, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x4f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x21, 0x0a, 0x0d, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x65, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x22, 0x22, 0x0a, 0x0e, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x68, 0x75, 0x72, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22,
	0x13, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x75, 0x72, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x75, 0x72,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x73, 0x70, 0x22, 0x28, 0x0a, 0x14, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4f, 0x63, 0x63, 0x75,
	0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22, 0x19,
	0x0a, 0x17, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x73, 0x70, 0x32, 0xa3, 0x02, 0x0a, 0x09, 0x42, 0x69,
	0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x41,
	0x0a, 0x0d, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12,
	0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x73,
	0x70, 0x12, 0x44, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x75, 0x72, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x12, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x68, 0x75, 0x72, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x75, 0x72, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x56, 0x0a, 0x14, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x4f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x1e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4f, 0x63, 0x63,
	0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x1e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4f, 0x63, 0x63,
	0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x73, 0x70, 0x42,
	0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_billSvr_proto_rawDescOnce sync.Once
	file_billSvr_proto_rawDescData = file_billSvr_proto_rawDesc
)

func file_billSvr_proto_rawDescGZIP() []byte {
	file_billSvr_proto_rawDescOnce.Do(func() {
		file_billSvr_proto_rawDescData = protoimpl.X.CompressGZIP(file_billSvr_proto_rawDescData)
	})
	return file_billSvr_proto_rawDescData
}

var file_billSvr_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_billSvr_proto_goTypes = []interface{}{
	(*UserStats)(nil),               // 0: model.UserStats
	(*UserStatsReq)(nil),            // 1: model.UserStatsReq
	(*UserStatsRsp)(nil),            // 2: model.UserStatsRsp
	(*RetainedUsers)(nil),           // 3: model.RetainedUsers
	(*RetainedUsersReq)(nil),        // 4: model.RetainedUsersReq
	(*RetainedUsersRsp)(nil),        // 5: model.RetainedUsersRsp
	(*UserChurnStats)(nil),          // 6: model.UserChurnStats
	(*UserChurnStatsReq)(nil),       // 7: model.UserChurnStatsReq
	(*UserChurnStatsRsp)(nil),       // 8: model.UserChurnStatsRsp
	(*SceneOccupationStats)(nil),    // 9: model.SceneOccupationStats
	(*SceneOccupationStatsReq)(nil), // 10: model.SceneOccupationStatsReq
	(*SceneOccupationStatsRsp)(nil), // 11: model.SceneOccupationStatsRsp
}
var file_billSvr_proto_depIdxs = []int32{
	1,  // 0: model.BillStats.UserStats:input_type -> model.UserStatsReq
	4,  // 1: model.BillStats.RetainedUsers:input_type -> model.RetainedUsersReq
	7,  // 2: model.BillStats.UserChurnStats:input_type -> model.UserChurnStatsReq
	10, // 3: model.BillStats.SceneOccupationStats:input_type -> model.SceneOccupationStatsReq
	2,  // 4: model.BillStats.UserStats:output_type -> model.UserStatsRsp
	5,  // 5: model.BillStats.RetainedUsers:output_type -> model.RetainedUsersRsp
	8,  // 6: model.BillStats.UserChurnStats:output_type -> model.UserChurnStatsRsp
	11, // 7: model.BillStats.SceneOccupationStats:output_type -> model.SceneOccupationStatsRsp
	4,  // [4:8] is the sub-list for method output_type
	0,  // [0:4] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_billSvr_proto_init() }
func file_billSvr_proto_init() {
	if File_billSvr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_billSvr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billSvr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billSvr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStatsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billSvr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetainedUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billSvr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetainedUsersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billSvr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetainedUsersRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billSvr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserChurnStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billSvr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserChurnStatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billSvr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserChurnStatsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billSvr_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneOccupationStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billSvr_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneOccupationStatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billSvr_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneOccupationStatsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_billSvr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billSvr_proto_goTypes,
		DependencyIndexes: file_billSvr_proto_depIdxs,
		MessageInfos:      file_billSvr_proto_msgTypes,
	}.Build()
	File_billSvr_proto = out.File
	file_billSvr_proto_rawDesc = nil
	file_billSvr_proto_goTypes = nil
	file_billSvr_proto_depIdxs = nil
}
