// protoc --proto_path=./pb --go_out=./pbgo --go_opt=paths=source_relative ./pb/billStats.proto
// protoc-go-inject-tag -input="./pbgo/billStats.pb.go"
// goctl model mongo -e -dir ./model -t LoginBill --home template -c
// goctl model mongo -e -dir ./model -t DayBaseSummaryStatsDB --home template -c
// goctl model mongo -e -dir ./model -t DayRetainStatsDB --home template -c
// goctl model mongo -e -dir ./model -t DayUserLvStatsDB --home template -c
// goctl model mongo -e -dir ./model -t DayUserTaskStatsDB --home template -c
// goctl model mongo -e -dir ./model -t ItemFlowBill --home template -c
//!!!!!!! 删除生成的worldtypes, 代码成替换成model对象

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: billStats.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 每天的概况汇总
type DayBaseSummaryStatsDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Day string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	// @inject_tag: bson:"totalRegister"
	TotalRegister uint32 `protobuf:"varint,2,opt,name=totalRegister,proto3" json:"totalRegister,omitempty"` // 历史注册
	// @inject_tag: bson:"registerUser"
	RegisterUser uint32 `protobuf:"varint,3,opt,name=registerUser,proto3" json:"registerUser,omitempty"` // 当日注册
	// @inject_tag: bson:"activeUser"
	ActiveUser uint32 `protobuf:"varint,4,opt,name=activeUser,proto3" json:"activeUser,omitempty"` // 当日活跃
	// @inject_tag: bson:"paidUser"
	PaidUser uint32 `protobuf:"varint,5,opt,name=paidUser,proto3" json:"paidUser,omitempty"` // 当日付费用户数
	// @inject_tag: bson:"paidTimes"
	PaidTimes uint32 `protobuf:"varint,6,opt,name=paidTimes,proto3" json:"paidTimes,omitempty"` // 当日付费次数数
	// @inject_tag: bson:"paidAmount"
	PaidAmount uint32 `protobuf:"varint,7,opt,name=paidAmount,proto3" json:"paidAmount,omitempty"` // 当日付费额度
}

func (x *DayBaseSummaryStatsDB) Reset() {
	*x = DayBaseSummaryStatsDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billStats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayBaseSummaryStatsDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayBaseSummaryStatsDB) ProtoMessage() {}

func (x *DayBaseSummaryStatsDB) ProtoReflect() protoreflect.Message {
	mi := &file_billStats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayBaseSummaryStatsDB.ProtoReflect.Descriptor instead.
func (*DayBaseSummaryStatsDB) Descriptor() ([]byte, []int) {
	return file_billStats_proto_rawDescGZIP(), []int{0}
}

func (x *DayBaseSummaryStatsDB) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DayBaseSummaryStatsDB) GetTotalRegister() uint32 {
	if x != nil {
		return x.TotalRegister
	}
	return 0
}

func (x *DayBaseSummaryStatsDB) GetRegisterUser() uint32 {
	if x != nil {
		return x.RegisterUser
	}
	return 0
}

func (x *DayBaseSummaryStatsDB) GetActiveUser() uint32 {
	if x != nil {
		return x.ActiveUser
	}
	return 0
}

func (x *DayBaseSummaryStatsDB) GetPaidUser() uint32 {
	if x != nil {
		return x.PaidUser
	}
	return 0
}

func (x *DayBaseSummaryStatsDB) GetPaidTimes() uint32 {
	if x != nil {
		return x.PaidTimes
	}
	return 0
}

func (x *DayBaseSummaryStatsDB) GetPaidAmount() uint32 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

// 每天的留存统计
type DayRetainStatsDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Day string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	// @inject_tag: bson:"registerCnt"
	RegisterCnt uint32 `protobuf:"varint,2,opt,name=registerCnt,proto3" json:"registerCnt,omitempty"` // 当日注册
	// @inject_tag: bson:"dayRetainCnt"
	DayRetainCnt []uint32 `protobuf:"varint,3,rep,packed,name=dayRetainCnt,proto3" json:"dayRetainCnt,omitempty"`
}

func (x *DayRetainStatsDB) Reset() {
	*x = DayRetainStatsDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billStats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayRetainStatsDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayRetainStatsDB) ProtoMessage() {}

func (x *DayRetainStatsDB) ProtoReflect() protoreflect.Message {
	mi := &file_billStats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayRetainStatsDB.ProtoReflect.Descriptor instead.
func (*DayRetainStatsDB) Descriptor() ([]byte, []int) {
	return file_billStats_proto_rawDescGZIP(), []int{1}
}

func (x *DayRetainStatsDB) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DayRetainStatsDB) GetRegisterCnt() uint32 {
	if x != nil {
		return x.RegisterCnt
	}
	return 0
}

func (x *DayRetainStatsDB) GetDayRetainCnt() []uint32 {
	if x != nil {
		return x.DayRetainCnt
	}
	return nil
}

// 每天的等级驻留统计
type DayUserLvStatsDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Day string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	// @inject_tag: bson:"totalRegister"
	TotalRegister uint32 `protobuf:"varint,2,opt,name=totalRegister,proto3" json:"totalRegister,omitempty"` // 历史注册
	// @inject_tag: bson:"registerUser"
	RegisterUser uint32 `protobuf:"varint,3,opt,name=registerUser,proto3" json:"registerUser,omitempty"` // 当日注册
	// @inject_tag: bson:"dayLvCnt"
	DayLvCnt []uint32 `protobuf:"varint,4,rep,packed,name=dayLvCnt,proto3" json:"dayLvCnt,omitempty"` // 停留在每个等级的人数(下标0对应等级1)
}

func (x *DayUserLvStatsDB) Reset() {
	*x = DayUserLvStatsDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billStats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayUserLvStatsDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayUserLvStatsDB) ProtoMessage() {}

func (x *DayUserLvStatsDB) ProtoReflect() protoreflect.Message {
	mi := &file_billStats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayUserLvStatsDB.ProtoReflect.Descriptor instead.
func (*DayUserLvStatsDB) Descriptor() ([]byte, []int) {
	return file_billStats_proto_rawDescGZIP(), []int{2}
}

func (x *DayUserLvStatsDB) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DayUserLvStatsDB) GetTotalRegister() uint32 {
	if x != nil {
		return x.TotalRegister
	}
	return 0
}

func (x *DayUserLvStatsDB) GetRegisterUser() uint32 {
	if x != nil {
		return x.RegisterUser
	}
	return 0
}

func (x *DayUserLvStatsDB) GetDayLvCnt() []uint32 {
	if x != nil {
		return x.DayLvCnt
	}
	return nil
}

// 每天的场景驻留统计
type DayUserTaskStatsDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Day string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	// @inject_tag: bson:"totalRegister"
	TotalRegister uint32 `protobuf:"varint,2,opt,name=totalRegister,proto3" json:"totalRegister,omitempty"` // 历史注册
	// @inject_tag: bson:"registerUser"
	RegisterUser uint32 `protobuf:"varint,3,opt,name=registerUser,proto3" json:"registerUser,omitempty"` // 当日注册
	// @inject_tag: bson:"dayTaskCnt"
	DayTaskCnt []uint32 `protobuf:"varint,4,rep,packed,name=dayTaskCnt,proto3" json:"dayTaskCnt,omitempty"` // 停留在每个任务的人数(下标0对应任务1)
}

func (x *DayUserTaskStatsDB) Reset() {
	*x = DayUserTaskStatsDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billStats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayUserTaskStatsDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayUserTaskStatsDB) ProtoMessage() {}

func (x *DayUserTaskStatsDB) ProtoReflect() protoreflect.Message {
	mi := &file_billStats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayUserTaskStatsDB.ProtoReflect.Descriptor instead.
func (*DayUserTaskStatsDB) Descriptor() ([]byte, []int) {
	return file_billStats_proto_rawDescGZIP(), []int{3}
}

func (x *DayUserTaskStatsDB) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DayUserTaskStatsDB) GetTotalRegister() uint32 {
	if x != nil {
		return x.TotalRegister
	}
	return 0
}

func (x *DayUserTaskStatsDB) GetRegisterUser() uint32 {
	if x != nil {
		return x.RegisterUser
	}
	return 0
}

func (x *DayUserTaskStatsDB) GetDayTaskCnt() []uint32 {
	if x != nil {
		return x.DayTaskCnt
	}
	return nil
}

// 道具流水账单
type ItemFlowBill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"uid"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @inject_tag: bson:"timeStamp"
	TimeStamp uint32 `protobuf:"varint,2,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"` // 道具变化时间
	// @inject_tag: bson:"globalItemId"
	GlobalItemId uint32 `protobuf:"varint,3,opt,name=globalItemId,proto3" json:"globalItemId,omitempty"`
	// @inject_tag: bson:"isSub"
	IsSub bool `protobuf:"varint,4,opt,name=isSub,proto3" json:"isSub,omitempty"` // 0增加 1减少
	// @inject_tag: bson:"count"
	Count uint32 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	// @inject_tag: bson:"afterCount"
	AfterCount uint32 `protobuf:"varint,6,opt,name=afterCount,proto3" json:"afterCount,omitempty"`
	// @inject_tag: bson:"reason"
	Reason EUserOperId `protobuf:"varint,7,opt,name=reason,proto3,enum=model.EUserOperId" json:"reason,omitempty"`
	// @inject_tag: bson:"subReason"
	SubReason uint32 `protobuf:"varint,8,opt,name=subReason,proto3" json:"subReason,omitempty"`
}

func (x *ItemFlowBill) Reset() {
	*x = ItemFlowBill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billStats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemFlowBill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemFlowBill) ProtoMessage() {}

func (x *ItemFlowBill) ProtoReflect() protoreflect.Message {
	mi := &file_billStats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemFlowBill.ProtoReflect.Descriptor instead.
func (*ItemFlowBill) Descriptor() ([]byte, []int) {
	return file_billStats_proto_rawDescGZIP(), []int{4}
}

func (x *ItemFlowBill) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ItemFlowBill) GetTimeStamp() uint32 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *ItemFlowBill) GetGlobalItemId() uint32 {
	if x != nil {
		return x.GlobalItemId
	}
	return 0
}

func (x *ItemFlowBill) GetIsSub() bool {
	if x != nil {
		return x.IsSub
	}
	return false
}

func (x *ItemFlowBill) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemFlowBill) GetAfterCount() uint32 {
	if x != nil {
		return x.AfterCount
	}
	return 0
}

func (x *ItemFlowBill) GetReason() EUserOperId {
	if x != nil {
		return x.Reason
	}
	return EUserOperId_EPOI_Invalid
}

func (x *ItemFlowBill) GetSubReason() uint32 {
	if x != nil {
		return x.SubReason
	}
	return 0
}

// 登录账单
type LoginBill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"uid"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @inject_tag: bson:"openId"
	OpenId string `protobuf:"bytes,2,opt,name=openId,proto3" json:"openId,omitempty"`
	// @inject_tag: bson:"registerTime"
	RegisterTime uint32 `protobuf:"varint,3,opt,name=registerTime,proto3" json:"registerTime,omitempty"`
	// @inject_tag: bson:"loginTime"
	LoginTime uint32 `protobuf:"varint,4,opt,name=loginTime,proto3" json:"loginTime,omitempty"`
	// @inject_tag: bson:"logoutTime"
	LogoutTime uint32 `protobuf:"varint,5,opt,name=logoutTime,proto3" json:"logoutTime,omitempty"`
}

func (x *LoginBill) Reset() {
	*x = LoginBill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_billStats_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginBill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginBill) ProtoMessage() {}

func (x *LoginBill) ProtoReflect() protoreflect.Message {
	mi := &file_billStats_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginBill.ProtoReflect.Descriptor instead.
func (*LoginBill) Descriptor() ([]byte, []int) {
	return file_billStats_proto_rawDescGZIP(), []int{5}
}

func (x *LoginBill) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LoginBill) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *LoginBill) GetRegisterTime() uint32 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

func (x *LoginBill) GetLoginTime() uint32 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

func (x *LoginBill) GetLogoutTime() uint32 {
	if x != nil {
		return x.LogoutTime
	}
	return 0
}

var File_billStats_proto protoreflect.FileDescriptor

var file_billStats_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xed, 0x01, 0x0a, 0x15, 0x44, 0x61, 0x79, 0x42, 0x61,
	0x73, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x44, 0x42,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x61, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x70, 0x61, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x69, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x69,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x69, 0x64, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x61, 0x69, 0x64,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6a, 0x0a, 0x10, 0x44, 0x61, 0x79, 0x52, 0x65, 0x74,
	0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x44, 0x42, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x20, 0x0a, 0x0b,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6e, 0x74, 0x12, 0x22,
	0x0a, 0x0c, 0x64, 0x61, 0x79, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x43, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x0c, 0x64, 0x61, 0x79, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x43,
	0x6e, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x10, 0x44, 0x61, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x76,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x44, 0x42, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x22, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x79, 0x4c, 0x76, 0x43, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x61, 0x79, 0x4c, 0x76, 0x43, 0x6e, 0x74, 0x22,
	0x90, 0x01, 0x0a, 0x12, 0x44, 0x61, 0x79, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x44, 0x42, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x22,
	0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x61, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x43,
	0x6e, 0x74, 0x22, 0xf8, 0x01, 0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x46, 0x6c, 0x6f, 0x77, 0x42,
	0x69, 0x6c, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x53, 0x75, 0x62,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x53, 0x75, 0x62, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x66, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x66, 0x74, 0x65, 0x72, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x55, 0x73, 0x65,
	0x72, 0x4f, 0x70, 0x65, 0x72, 0x49, 0x64, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x73, 0x75, 0x62, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x97, 0x01,
	0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x6f, 0x75,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6c, 0x6f, 0x67,
	0x6f, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_billStats_proto_rawDescOnce sync.Once
	file_billStats_proto_rawDescData = file_billStats_proto_rawDesc
)

func file_billStats_proto_rawDescGZIP() []byte {
	file_billStats_proto_rawDescOnce.Do(func() {
		file_billStats_proto_rawDescData = protoimpl.X.CompressGZIP(file_billStats_proto_rawDescData)
	})
	return file_billStats_proto_rawDescData
}

var file_billStats_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_billStats_proto_goTypes = []interface{}{
	(*DayBaseSummaryStatsDB)(nil), // 0: model.DayBaseSummaryStatsDB
	(*DayRetainStatsDB)(nil),      // 1: model.DayRetainStatsDB
	(*DayUserLvStatsDB)(nil),      // 2: model.DayUserLvStatsDB
	(*DayUserTaskStatsDB)(nil),    // 3: model.DayUserTaskStatsDB
	(*ItemFlowBill)(nil),          // 4: model.ItemFlowBill
	(*LoginBill)(nil),             // 5: model.LoginBill
	(EUserOperId)(0),              // 6: model.EUserOperId
}
var file_billStats_proto_depIdxs = []int32{
	6, // 0: model.ItemFlowBill.reason:type_name -> model.EUserOperId
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_billStats_proto_init() }
func file_billStats_proto_init() {
	if File_billStats_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_billStats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayBaseSummaryStatsDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billStats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayRetainStatsDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billStats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayUserLvStatsDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billStats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayUserTaskStatsDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billStats_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemFlowBill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_billStats_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginBill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_billStats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_billStats_proto_goTypes,
		DependencyIndexes: file_billStats_proto_depIdxs,
		MessageInfos:      file_billStats_proto_msgTypes,
	}.Build()
	File_billStats_proto = out.File
	file_billStats_proto_rawDesc = nil
	file_billStats_proto_goTypes = nil
	file_billStats_proto_depIdxs = nil
}
