// protoc --proto_path=./pb --go_out=./pbgo --go_opt=paths=source_relative ./pb/clientReport.proto
// protoc-go-inject-tag -input="./pbgo/clientReport.pb.go"
// goctl model mongo -e -dir ./model -t ClientReport --home template -c
//!!!!!!! 删除生成的worldtypes, 代码成替换成model对象

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: clientReport.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"openId"
	OpenId string `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	// @inject_tag: bson:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// @inject_tag: bson:"level"
	Level string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	// @inject_tag: bson:"ext1"
	Ext1 string `protobuf:"bytes,4,opt,name=ext1,proto3" json:"ext1,omitempty"`
	// @inject_tag: bson:"ext2"
	Ext2 string `protobuf:"bytes,5,opt,name=ext2,proto3" json:"ext2,omitempty"`
	// @inject_tag: bson:"ext3"
	Ext3 string `protobuf:"bytes,6,opt,name=ext3,proto3" json:"ext3,omitempty"`
	// @inject_tag: bson:"trace"
	Trace string `protobuf:"bytes,7,opt,name=trace,proto3" json:"trace,omitempty"`
	// @inject_tag: bson:"createTime"
	CreateTime int64 `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *ClientReport) Reset() {
	*x = ClientReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientReport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReport) ProtoMessage() {}

func (x *ClientReport) ProtoReflect() protoreflect.Message {
	mi := &file_clientReport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReport.ProtoReflect.Descriptor instead.
func (*ClientReport) Descriptor() ([]byte, []int) {
	return file_clientReport_proto_rawDescGZIP(), []int{0}
}

func (x *ClientReport) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *ClientReport) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ClientReport) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ClientReport) GetExt1() string {
	if x != nil {
		return x.Ext1
	}
	return ""
}

func (x *ClientReport) GetExt2() string {
	if x != nil {
		return x.Ext2
	}
	return ""
}

func (x *ClientReport) GetExt3() string {
	if x != nil {
		return x.Ext3
	}
	return ""
}

func (x *ClientReport) GetTrace() string {
	if x != nil {
		return x.Trace
	}
	return ""
}

func (x *ClientReport) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

var File_clientReport_proto protoreflect.FileDescriptor

var file_clientReport_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xc0, 0x01, 0x0a, 0x0c,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70,
	0x65, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x65, 0x78, 0x74, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x78, 0x74, 0x31,
	0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x74, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x65, 0x78, 0x74, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x74, 0x33, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x65, 0x78, 0x74, 0x33, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0d,
	0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientReport_proto_rawDescOnce sync.Once
	file_clientReport_proto_rawDescData = file_clientReport_proto_rawDesc
)

func file_clientReport_proto_rawDescGZIP() []byte {
	file_clientReport_proto_rawDescOnce.Do(func() {
		file_clientReport_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientReport_proto_rawDescData)
	})
	return file_clientReport_proto_rawDescData
}

var file_clientReport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clientReport_proto_goTypes = []interface{}{
	(*ClientReport)(nil), // 0: model.ClientReport
}
var file_clientReport_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clientReport_proto_init() }
func file_clientReport_proto_init() {
	if File_clientReport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientReport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientReport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clientReport_proto_goTypes,
		DependencyIndexes: file_clientReport_proto_depIdxs,
		MessageInfos:      file_clientReport_proto_msgTypes,
	}.Build()
	File_clientReport_proto = out.File
	file_clientReport_proto_rawDesc = nil
	file_clientReport_proto_goTypes = nil
	file_clientReport_proto_depIdxs = nil
}
