// protoc --proto_path=./pb --go_out=./pbgo --go_opt=paths=source_relative ./pb/dailySign.proto
// protoc-go-inject-tag -input="./pbgo/dailySign.pb.go"
// goctl model mongo -e -dir ./model -t DailySign --home template -c
//!!!!!!! 删除生成的worldtypes, 代码成替换成model对象

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: dailySign.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EDailySignState int32

const (
	EDailySignState_EDSS_None      EDailySignState = 0
	EDailySignState_EDSS_Signed    EDailySignState = 1
	EDailySignState_EDSS_CanSign   EDailySignState = 2
	EDailySignState_EDSS_ReSigned  EDailySignState = 3
	EDailySignState_EDSS_CanReSign EDailySignState = 4
)

// Enum value maps for EDailySignState.
var (
	EDailySignState_name = map[int32]string{
		0: "EDSS_None",
		1: "EDSS_Signed",
		2: "EDSS_CanSign",
		3: "EDSS_ReSigned",
		4: "EDSS_CanReSign",
	}
	EDailySignState_value = map[string]int32{
		"EDSS_None":      0,
		"EDSS_Signed":    1,
		"EDSS_CanSign":   2,
		"EDSS_ReSigned":  3,
		"EDSS_CanReSign": 4,
	}
)

func (x EDailySignState) Enum() *EDailySignState {
	p := new(EDailySignState)
	*p = x
	return p
}

func (x EDailySignState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EDailySignState) Descriptor() protoreflect.EnumDescriptor {
	return file_dailySign_proto_enumTypes[0].Descriptor()
}

func (EDailySignState) Type() protoreflect.EnumType {
	return &file_dailySign_proto_enumTypes[0]
}

func (x EDailySignState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EDailySignState.Descriptor instead.
func (EDailySignState) EnumDescriptor() ([]byte, []int) {
	return file_dailySign_proto_rawDescGZIP(), []int{0}
}

type DailySign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @inject_tag: bson:"lastActDataClearTime"
	LastActDataClearTime uint32 `protobuf:"varint,2,opt,name=lastActDataClearTime,proto3" json:"lastActDataClearTime,omitempty"`
	// @inject_tag: bson:"dailySignList"
	DailySignList []EDailySignState `protobuf:"varint,3,rep,packed,name=dailySignList,proto3,enum=model.EDailySignState" json:"dailySignList,omitempty"`
	// @inject_tag: bson:"seq"
	Seq uint64 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *DailySign) Reset() {
	*x = DailySign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dailySign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailySign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailySign) ProtoMessage() {}

func (x *DailySign) ProtoReflect() protoreflect.Message {
	mi := &file_dailySign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailySign.ProtoReflect.Descriptor instead.
func (*DailySign) Descriptor() ([]byte, []int) {
	return file_dailySign_proto_rawDescGZIP(), []int{0}
}

func (x *DailySign) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DailySign) GetLastActDataClearTime() uint32 {
	if x != nil {
		return x.LastActDataClearTime
	}
	return 0
}

func (x *DailySign) GetDailySignList() []EDailySignState {
	if x != nil {
		return x.DailySignList
	}
	return nil
}

func (x *DailySign) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_dailySign_proto protoreflect.FileDescriptor

var file_dailySign_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xa1, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x69,
	0x6c, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x14, 0x6c, 0x61, 0x73, 0x74,
	0x41, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x63, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0d,
	0x64, 0x61, 0x69, 0x6c, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x44, 0x61, 0x69,
	0x6c, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x64, 0x61, 0x69,
	0x6c, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x2a, 0x6a, 0x0a, 0x0f,
	0x45, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x0d, 0x0a, 0x09, 0x45, 0x44, 0x53, 0x53, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x45, 0x44, 0x53, 0x53, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x10, 0x01, 0x12,
	0x10, 0x0a, 0x0c, 0x45, 0x44, 0x53, 0x53, 0x5f, 0x43, 0x61, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x10,
	0x02, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x44, 0x53, 0x53, 0x5f, 0x52, 0x65, 0x53, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x44, 0x53, 0x53, 0x5f, 0x43, 0x61, 0x6e,
	0x52, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x10, 0x04, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dailySign_proto_rawDescOnce sync.Once
	file_dailySign_proto_rawDescData = file_dailySign_proto_rawDesc
)

func file_dailySign_proto_rawDescGZIP() []byte {
	file_dailySign_proto_rawDescOnce.Do(func() {
		file_dailySign_proto_rawDescData = protoimpl.X.CompressGZIP(file_dailySign_proto_rawDescData)
	})
	return file_dailySign_proto_rawDescData
}

var file_dailySign_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dailySign_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dailySign_proto_goTypes = []interface{}{
	(EDailySignState)(0), // 0: model.EDailySignState
	(*DailySign)(nil),    // 1: model.DailySign
}
var file_dailySign_proto_depIdxs = []int32{
	0, // 0: model.DailySign.dailySignList:type_name -> model.EDailySignState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dailySign_proto_init() }
func file_dailySign_proto_init() {
	if File_dailySign_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dailySign_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailySign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dailySign_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dailySign_proto_goTypes,
		DependencyIndexes: file_dailySign_proto_depIdxs,
		EnumInfos:         file_dailySign_proto_enumTypes,
		MessageInfos:      file_dailySign_proto_msgTypes,
	}.Build()
	File_dailySign_proto = out.File
	file_dailySign_proto_rawDesc = nil
	file_dailySign_proto_goTypes = nil
	file_dailySign_proto_depIdxs = nil
}
