// protoc --proto_path=./pb --go_out=./pbgo --go_opt=paths=source_relative ./pb/email.proto
// protoc-go-inject-tag -input="./pbgo/email.pb.go"
// goctl model mongo -e -dir ./model -t EmailCfg --home template -c

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: email.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EEmailType int32

const (
	EEmailType_EMAIL_SYSTEM EEmailType = 0
)

// Enum value maps for EEmailType.
var (
	EEmailType_name = map[int32]string{
		0: "EMAIL_SYSTEM",
	}
	EEmailType_value = map[string]int32{
		"EMAIL_SYSTEM": 0,
	}
)

func (x EEmailType) Enum() *EEmailType {
	p := new(EEmailType)
	*p = x
	return p
}

func (x EEmailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EEmailType) Descriptor() protoreflect.EnumDescriptor {
	return file_email_proto_enumTypes[0].Descriptor()
}

func (EEmailType) Type() protoreflect.EnumType {
	return &file_email_proto_enumTypes[0]
}

func (x EEmailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EEmailType.Descriptor instead.
func (EEmailType) EnumDescriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0}
}

type EmailInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"id"
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: bson:"type"
	Type EEmailType `protobuf:"varint,2,opt,name=type,proto3,enum=model.EEmailType" json:"type,omitempty"`
	// @inject_tag: bson:"sendTime"
	SendTime uint32 `protobuf:"varint,3,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	// @inject_tag: bson:"readStatus"
	ReadStatus bool `protobuf:"varint,4,opt,name=readStatus,proto3" json:"readStatus,omitempty"`
	// @inject_tag: bson:"awardList"
	AwardList []*ItemInfo `protobuf:"bytes,5,rep,name=awardList,proto3" json:"awardList,omitempty"`
	// @inject_tag: bson:"awardStatus"
	AwardStatus bool `protobuf:"varint,6,opt,name=awardStatus,proto3" json:"awardStatus,omitempty"`
	// @inject_tag: bson:"title"
	Title string `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	// @inject_tag: bson:"content"
	Content string `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	// @inject_tag: bson:"expireTime"
	ExpireTime uint32 `protobuf:"varint,9,opt,name=expireTime,proto3" json:"expireTime,omitempty"` //过期时间戳
}

func (x *EmailInfo) Reset() {
	*x = EmailInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_email_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailInfo) ProtoMessage() {}

func (x *EmailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailInfo.ProtoReflect.Descriptor instead.
func (*EmailInfo) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0}
}

func (x *EmailInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmailInfo) GetType() EEmailType {
	if x != nil {
		return x.Type
	}
	return EEmailType_EMAIL_SYSTEM
}

func (x *EmailInfo) GetSendTime() uint32 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *EmailInfo) GetReadStatus() bool {
	if x != nil {
		return x.ReadStatus
	}
	return false
}

func (x *EmailInfo) GetAwardList() []*ItemInfo {
	if x != nil {
		return x.AwardList
	}
	return nil
}

func (x *EmailInfo) GetAwardStatus() bool {
	if x != nil {
		return x.AwardStatus
	}
	return false
}

func (x *EmailInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EmailInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmailInfo) GetExpireTime() uint32 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type EmailCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //邮件id
	// @inject_tag: bson:"esTime"
	EffectStartTime uint32 `protobuf:"varint,2,opt,name=effectStartTime,proto3" json:"effectStartTime,omitempty"` //生效开始时间
	// @inject_tag: bson:"eeTime"
	EffectEndTime uint32 `protobuf:"varint,3,opt,name=effectEndTime,proto3" json:"effectEndTime,omitempty"` //生效结束时间
	// @inject_tag: bson:"cTime"
	CreateTime uint32 `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"` //创建时间
	// @inject_tag: bson:"type"
	Type EEmailType `protobuf:"varint,5,opt,name=type,proto3,enum=model.EEmailType" json:"type,omitempty"` //邮件类型
	// @inject_tag: bson:"title"
	Title string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"` //邮件标题
	// @inject_tag: bson:"content"
	Content string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"` //邮件内容
	// @inject_tag: bson:"awards"
	Awards []*ItemInfo `protobuf:"bytes,8,rep,name=awards,proto3" json:"awards,omitempty"` //邮件奖励
	// @inject_tag: bson:"uLvl"
	UserLvl uint32 `protobuf:"varint,9,opt,name=userLvl,proto3" json:"userLvl,omitempty"` //用户等级限制
	// @inject_tag: bson:"vTime"
	ValidTime uint32 `protobuf:"varint,10,opt,name=validTime,proto3" json:"validTime,omitempty"` //有效时间(秒)
}

func (x *EmailCfg) Reset() {
	*x = EmailCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_email_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCfg) ProtoMessage() {}

func (x *EmailCfg) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCfg.ProtoReflect.Descriptor instead.
func (*EmailCfg) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{1}
}

func (x *EmailCfg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmailCfg) GetEffectStartTime() uint32 {
	if x != nil {
		return x.EffectStartTime
	}
	return 0
}

func (x *EmailCfg) GetEffectEndTime() uint32 {
	if x != nil {
		return x.EffectEndTime
	}
	return 0
}

func (x *EmailCfg) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *EmailCfg) GetType() EEmailType {
	if x != nil {
		return x.Type
	}
	return EEmailType_EMAIL_SYSTEM
}

func (x *EmailCfg) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EmailCfg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmailCfg) GetAwards() []*ItemInfo {
	if x != nil {
		return x.Awards
	}
	return nil
}

func (x *EmailCfg) GetUserLvl() uint32 {
	if x != nil {
		return x.UserLvl
	}
	return 0
}

func (x *EmailCfg) GetValidTime() uint32 {
	if x != nil {
		return x.ValidTime
	}
	return 0
}

var File_email_proto protoreflect.FileDescriptor

var file_email_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x0e, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x02, 0x0a, 0x09, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x61, 0x77, 0x61, 0x72, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61, 0x77, 0x61, 0x72, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x77, 0x61, 0x72, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x61, 0x77, 0x61, 0x72, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xc2, 0x02, 0x0a, 0x08, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x43, 0x66, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x65, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x45, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x61, 0x77,
	0x61, 0x72, 0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x61, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x76, 0x6c, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x76, 0x6c, 0x12, 0x1c, 0x0a,
	0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x2a, 0x1e, 0x0a, 0x0a, 0x45,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x4d, 0x41,
	0x49, 0x4c, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_email_proto_rawDescOnce sync.Once
	file_email_proto_rawDescData = file_email_proto_rawDesc
)

func file_email_proto_rawDescGZIP() []byte {
	file_email_proto_rawDescOnce.Do(func() {
		file_email_proto_rawDescData = protoimpl.X.CompressGZIP(file_email_proto_rawDescData)
	})
	return file_email_proto_rawDescData
}

var file_email_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_email_proto_goTypes = []interface{}{
	(EEmailType)(0),   // 0: model.EEmailType
	(*EmailInfo)(nil), // 1: model.EmailInfo
	(*EmailCfg)(nil),  // 2: model.EmailCfg
	(*ItemInfo)(nil),  // 3: model.ItemInfo
}
var file_email_proto_depIdxs = []int32{
	0, // 0: model.EmailInfo.type:type_name -> model.EEmailType
	3, // 1: model.EmailInfo.awardList:type_name -> model.ItemInfo
	0, // 2: model.EmailCfg.type:type_name -> model.EEmailType
	3, // 3: model.EmailCfg.awards:type_name -> model.ItemInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_email_proto_init() }
func file_email_proto_init() {
	if File_email_proto != nil {
		return
	}
	file_itemInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_email_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_email_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_email_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_email_proto_goTypes,
		DependencyIndexes: file_email_proto_depIdxs,
		EnumInfos:         file_email_proto_enumTypes,
		MessageInfos:      file_email_proto_msgTypes,
	}.Build()
	File_email_proto = out.File
	file_email_proto_rawDesc = nil
	file_email_proto_goTypes = nil
	file_email_proto_depIdxs = nil
}
