// protoc --proto_path=./docproj/msg --go_out=./pbgo --go_opt=paths=source_relative ./docproj/msg/eventStats.proto
// protoc-go-inject-tag -input="./pbgo/eventStats.pb.go"
// goctl model mongo -e -dir ./model -t EventStats --home template -c
// goctl model mongo -e -dir ./model -t EventStatIds --home template -c
//!!!!!!! 删除生成的worldtypes, 代码成替换成model对象

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: eventStats.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventStatsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"statsId"
	StatsId uint32 `protobuf:"varint,1,opt,name=statsId,proto3" json:"statsId,omitempty"`
	// @inject_tag: bson:"statsCnt"
	StatsCnt uint32 `protobuf:"varint,2,opt,name=statsCnt,proto3" json:"statsCnt,omitempty"` //! 统计数量
	// @inject_tag: bson:"updateTime"
	UpdateTime uint32 `protobuf:"varint,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"` //! 统计更新时间
}

func (x *EventStatsItem) Reset() {
	*x = EventStatsItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventStats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventStatsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStatsItem) ProtoMessage() {}

func (x *EventStatsItem) ProtoReflect() protoreflect.Message {
	mi := &file_eventStats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStatsItem.ProtoReflect.Descriptor instead.
func (*EventStatsItem) Descriptor() ([]byte, []int) {
	return file_eventStats_proto_rawDescGZIP(), []int{0}
}

func (x *EventStatsItem) GetStatsId() uint32 {
	if x != nil {
		return x.StatsId
	}
	return 0
}

func (x *EventStatsItem) GetStatsCnt() uint32 {
	if x != nil {
		return x.StatsCnt
	}
	return 0
}

func (x *EventStatsItem) GetUpdateTime() uint32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type EventStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @inject_tag: bson:"eventStatsList"
	EventStatsList []*EventStatsItem `protobuf:"bytes,2,rep,name=eventStatsList,proto3" json:"eventStatsList,omitempty"`
	// @inject_tag: bson:"seq"
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *EventStats) Reset() {
	*x = EventStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventStats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStats) ProtoMessage() {}

func (x *EventStats) ProtoReflect() protoreflect.Message {
	mi := &file_eventStats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStats.ProtoReflect.Descriptor instead.
func (*EventStats) Descriptor() ([]byte, []int) {
	return file_eventStats_proto_rawDescGZIP(), []int{1}
}

func (x *EventStats) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *EventStats) GetEventStatsList() []*EventStatsItem {
	if x != nil {
		return x.EventStatsList
	}
	return nil
}

func (x *EventStats) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// 这个活动任务的统计还需要看玩家是否领取这个stat, 还需要需要维护一个玩家的statIdList的表
type EventStatIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @inject_tag: bson:"statsIds"
	StatsIds []uint32 `protobuf:"varint,2,rep,packed,name=statsIds,proto3" json:"statsIds,omitempty"`
}

func (x *EventStatIds) Reset() {
	*x = EventStatIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventStats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventStatIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStatIds) ProtoMessage() {}

func (x *EventStatIds) ProtoReflect() protoreflect.Message {
	mi := &file_eventStats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStatIds.ProtoReflect.Descriptor instead.
func (*EventStatIds) Descriptor() ([]byte, []int) {
	return file_eventStats_proto_rawDescGZIP(), []int{2}
}

func (x *EventStatIds) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *EventStatIds) GetStatsIds() []uint32 {
	if x != nil {
		return x.StatsIds
	}
	return nil
}

var File_eventStats_proto protoreflect.FileDescriptor

var file_eventStats_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x66, 0x0a, 0x0e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x74, 0x61, 0x74, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x73, 0x43, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x73, 0x43, 0x6e,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x6f, 0x0a, 0x0a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x3d, 0x0a, 0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73,
	0x65, 0x71, 0x22, 0x3c, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x49,
	0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x73, 0x49, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x73, 0x49, 0x64, 0x73,
	0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eventStats_proto_rawDescOnce sync.Once
	file_eventStats_proto_rawDescData = file_eventStats_proto_rawDesc
)

func file_eventStats_proto_rawDescGZIP() []byte {
	file_eventStats_proto_rawDescOnce.Do(func() {
		file_eventStats_proto_rawDescData = protoimpl.X.CompressGZIP(file_eventStats_proto_rawDescData)
	})
	return file_eventStats_proto_rawDescData
}

var file_eventStats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_eventStats_proto_goTypes = []interface{}{
	(*EventStatsItem)(nil), // 0: model.EventStatsItem
	(*EventStats)(nil),     // 1: model.EventStats
	(*EventStatIds)(nil),   // 2: model.EventStatIds
}
var file_eventStats_proto_depIdxs = []int32{
	0, // 0: model.EventStats.eventStatsList:type_name -> model.EventStatsItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_eventStats_proto_init() }
func file_eventStats_proto_init() {
	if File_eventStats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eventStats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventStatsItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventStats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventStats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventStatIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eventStats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eventStats_proto_goTypes,
		DependencyIndexes: file_eventStats_proto_depIdxs,
		MessageInfos:      file_eventStats_proto_msgTypes,
	}.Build()
	File_eventStats_proto = out.File
	file_eventStats_proto_rawDesc = nil
	file_eventStats_proto_goTypes = nil
	file_eventStats_proto_depIdxs = nil
}
