// protoc --proto_path=./pb --go_out=./pbgo --go_opt=paths=source_relative ./pb/itemInfo.proto
// protoc-go-inject-tag -input="./pbgo/itemInfo.pb.go"
// goctl model mongo -e -dir ./model -t Items --home template -c

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: itemInfo.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EItemId int32

const (
	EItemId_EII_Invalid  EItemId = 0
	EItemId_EII_PetStart EItemId = 60010000
	EItemId_EII_PetEnd   EItemId = 60019999
)

// Enum value maps for EItemId.
var (
	EItemId_name = map[int32]string{
		0:        "EII_Invalid",
		60010000: "EII_PetStart",
		60019999: "EII_PetEnd",
	}
	EItemId_value = map[string]int32{
		"EII_Invalid":  0,
		"EII_PetStart": 60010000,
		"EII_PetEnd":   60019999,
	}
)

func (x EItemId) Enum() *EItemId {
	p := new(EItemId)
	*p = x
	return p
}

func (x EItemId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EItemId) Descriptor() protoreflect.EnumDescriptor {
	return file_itemInfo_proto_enumTypes[0].Descriptor()
}

func (EItemId) Type() protoreflect.EnumType {
	return &file_itemInfo_proto_enumTypes[0]
}

func (x EItemId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EItemId.Descriptor instead.
func (EItemId) EnumDescriptor() ([]byte, []int) {
	return file_itemInfo_proto_rawDescGZIP(), []int{0}
}

type BaseItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"itemId"
	ItemId uint32 `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	// @inject_tag: bson:"num"
	Num uint32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *BaseItemInfo) Reset() {
	*x = BaseItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itemInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseItemInfo) ProtoMessage() {}

func (x *BaseItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_itemInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseItemInfo.ProtoReflect.Descriptor instead.
func (*BaseItemInfo) Descriptor() ([]byte, []int) {
	return file_itemInfo_proto_rawDescGZIP(), []int{0}
}

func (x *BaseItemInfo) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BaseItemInfo) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"globalItemId"
	GlobalItemId uint32 `protobuf:"varint,1,opt,name=globalItemId,proto3" json:"globalItemId,omitempty"`
	// @inject_tag: bson:"level"
	Level uint32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	// @inject_tag: bson:"itemType"
	ItemType uint32 `protobuf:"varint,3,opt,name=itemType,proto3" json:"itemType,omitempty"`
	// @inject_tag: bson:"num"
	Num uint32 `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	// @inject_tag: bson:"invalidTimeStamp"
	InvalidTimeStamp uint32 `protobuf:"varint,5,opt,name=invalidTimeStamp,proto3" json:"invalidTimeStamp,omitempty"`
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itemInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_itemInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_itemInfo_proto_rawDescGZIP(), []int{1}
}

func (x *ItemInfo) GetGlobalItemId() uint32 {
	if x != nil {
		return x.GlobalItemId
	}
	return 0
}

func (x *ItemInfo) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ItemInfo) GetItemType() uint32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *ItemInfo) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ItemInfo) GetInvalidTimeStamp() uint32 {
	if x != nil {
		return x.InvalidTimeStamp
	}
	return 0
}

type Items struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @inject_tag: bson:"itemList"
	ItemList []*ItemInfo `protobuf:"bytes,2,rep,name=itemList,proto3" json:"itemList,omitempty"`
	// @inject_tag: bson:"seq"
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *Items) Reset() {
	*x = Items{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itemInfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_itemInfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_itemInfo_proto_rawDescGZIP(), []int{2}
}

func (x *Items) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Items) GetItemList() []*ItemInfo {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *Items) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_itemInfo_proto protoreflect.FileDescriptor

var file_itemInfo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x38, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x22, 0x9e, 0x01, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22,
	0x0a, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x10, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x58, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x2b, 0x0a,
	0x08, 0x69, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x2a, 0x42, 0x0a, 0x07,
	0x45, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x49, 0x49, 0x5f, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0c, 0x45, 0x49, 0x49, 0x5f,
	0x50, 0x65, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10, 0x90, 0xdc, 0xce, 0x1c, 0x12, 0x11, 0x0a,
	0x0a, 0x45, 0x49, 0x49, 0x5f, 0x50, 0x65, 0x74, 0x45, 0x6e, 0x64, 0x10, 0x9f, 0xaa, 0xcf, 0x1c,
	0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_itemInfo_proto_rawDescOnce sync.Once
	file_itemInfo_proto_rawDescData = file_itemInfo_proto_rawDesc
)

func file_itemInfo_proto_rawDescGZIP() []byte {
	file_itemInfo_proto_rawDescOnce.Do(func() {
		file_itemInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_itemInfo_proto_rawDescData)
	})
	return file_itemInfo_proto_rawDescData
}

var file_itemInfo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_itemInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_itemInfo_proto_goTypes = []interface{}{
	(EItemId)(0),         // 0: model.EItemId
	(*BaseItemInfo)(nil), // 1: model.BaseItemInfo
	(*ItemInfo)(nil),     // 2: model.ItemInfo
	(*Items)(nil),        // 3: model.Items
}
var file_itemInfo_proto_depIdxs = []int32{
	2, // 0: model.Items.itemList:type_name -> model.ItemInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_itemInfo_proto_init() }
func file_itemInfo_proto_init() {
	if File_itemInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_itemInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itemInfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itemInfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Items); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_itemInfo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_itemInfo_proto_goTypes,
		DependencyIndexes: file_itemInfo_proto_depIdxs,
		EnumInfos:         file_itemInfo_proto_enumTypes,
		MessageInfos:      file_itemInfo_proto_msgTypes,
	}.Build()
	File_itemInfo_proto = out.File
	file_itemInfo_proto_rawDesc = nil
	file_itemInfo_proto_goTypes = nil
	file_itemInfo_proto_depIdxs = nil
}
