// protoc --proto_path=./pb --go_out=./pbgo --go_opt=paths=source_relative ./pb/mall.proto
// protoc-go-inject-tag -input="./pbgo/mall.pb.go"
// goctl model mongo -e -dir ./model -t Mall --home template -c
//!!!!!!! 删除生成的worldtypes, 代码成替换成model对象

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: mall.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MallItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"merchandiseId"
	MerchandiseId uint32 `protobuf:"varint,1,opt,name=merchandiseId,proto3" json:"merchandiseId,omitempty"`
	// @inject_tag: bson:"buyCnt"
	BuyCnt uint32 `protobuf:"varint,2,opt,name=buyCnt,proto3" json:"buyCnt,omitempty"` //! 已购买次数
	// @inject_tag: bson:"lastBuyTime"
	LastBuyTime uint32 `protobuf:"varint,3,opt,name=lastBuyTime,proto3" json:"lastBuyTime,omitempty"` //! 未刷新前购买时间戳
}

func (x *MallItem) Reset() {
	*x = MallItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MallItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallItem) ProtoMessage() {}

func (x *MallItem) ProtoReflect() protoreflect.Message {
	mi := &file_mall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallItem.ProtoReflect.Descriptor instead.
func (*MallItem) Descriptor() ([]byte, []int) {
	return file_mall_proto_rawDescGZIP(), []int{0}
}

func (x *MallItem) GetMerchandiseId() uint32 {
	if x != nil {
		return x.MerchandiseId
	}
	return 0
}

func (x *MallItem) GetBuyCnt() uint32 {
	if x != nil {
		return x.BuyCnt
	}
	return 0
}

func (x *MallItem) GetLastBuyTime() uint32 {
	if x != nil {
		return x.LastBuyTime
	}
	return 0
}

type Mall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @inject_tag: bson:"mallItemList"
	MallItemList []*MallItem `protobuf:"bytes,2,rep,name=mallItemList,proto3" json:"mallItemList,omitempty"`
	// @inject_tag: bson:"seq"
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *Mall) Reset() {
	*x = Mall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mall) ProtoMessage() {}

func (x *Mall) ProtoReflect() protoreflect.Message {
	mi := &file_mall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mall.ProtoReflect.Descriptor instead.
func (*Mall) Descriptor() ([]byte, []int) {
	return file_mall_proto_rawDescGZIP(), []int{1}
}

func (x *Mall) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Mall) GetMallItemList() []*MallItem {
	if x != nil {
		return x.MallItemList
	}
	return nil
}

func (x *Mall) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_mall_proto protoreflect.FileDescriptor

var file_mall_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0x6a, 0x0a, 0x08, 0x4d, 0x61, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x24, 0x0a, 0x0d, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x73, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x64,
	0x69, 0x73, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x79, 0x43, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x75, 0x79, 0x43, 0x6e, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x6c, 0x61, 0x73, 0x74, 0x42, 0x75, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x42, 0x75, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x5f, 0x0a, 0x04, 0x4d, 0x61, 0x6c, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x0c, 0x6d, 0x61, 0x6c,
	0x6c, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x61, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x0c, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71,
	0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mall_proto_rawDescOnce sync.Once
	file_mall_proto_rawDescData = file_mall_proto_rawDesc
)

func file_mall_proto_rawDescGZIP() []byte {
	file_mall_proto_rawDescOnce.Do(func() {
		file_mall_proto_rawDescData = protoimpl.X.CompressGZIP(file_mall_proto_rawDescData)
	})
	return file_mall_proto_rawDescData
}

var file_mall_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mall_proto_goTypes = []interface{}{
	(*MallItem)(nil), // 0: model.MallItem
	(*Mall)(nil),     // 1: model.Mall
}
var file_mall_proto_depIdxs = []int32{
	0, // 0: model.Mall.mallItemList:type_name -> model.MallItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mall_proto_init() }
func file_mall_proto_init() {
	if File_mall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MallItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mall_proto_goTypes,
		DependencyIndexes: file_mall_proto_depIdxs,
		MessageInfos:      file_mall_proto_msgTypes,
	}.Build()
	File_mall_proto = out.File
	file_mall_proto_rawDesc = nil
	file_mall_proto_goTypes = nil
	file_mall_proto_depIdxs = nil
}
