// protoc --proto_path=./pb --go_out=./pbgo --go_opt=paths=source_relative ./pb/pet.proto
// protoc-go-inject-tag -input="./pbgo/pet.pb.go"
// goctl model mongo -e -dir ./model -t Pet --home template -c
//!!!!!!! 删除生成的worldtypes, 代码成替换成model对象

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: pet.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EAttrType int32

const (
	EAttrType_EAV_INVALID EAttrType = 0 //! 无效
	EAttrType_EAV_SOCIAL  EAttrType = 1 //! 交际
	EAttrType_EAV_BREAD   EAttrType = 2 //! 培育
	EAttrType_EAV_PRODUCT EAttrType = 3 //! 生产
	EAttrType_EAV_LUCKY   EAttrType = 4 //! 幸运
	EAttrType_EAV_BUILD   EAttrType = 5 //! 建筑
	EAttrType_EAV_EXPLORE EAttrType = 6 //! 探索
	EAttrType_EAV_MAX     EAttrType = 7 //! 实际使用需要减1
)

// Enum value maps for EAttrType.
var (
	EAttrType_name = map[int32]string{
		0: "EAV_INVALID",
		1: "EAV_SOCIAL",
		2: "EAV_BREAD",
		3: "EAV_PRODUCT",
		4: "EAV_LUCKY",
		5: "EAV_BUILD",
		6: "EAV_EXPLORE",
		7: "EAV_MAX",
	}
	EAttrType_value = map[string]int32{
		"EAV_INVALID": 0,
		"EAV_SOCIAL":  1,
		"EAV_BREAD":   2,
		"EAV_PRODUCT": 3,
		"EAV_LUCKY":   4,
		"EAV_BUILD":   5,
		"EAV_EXPLORE": 6,
		"EAV_MAX":     7,
	}
)

func (x EAttrType) Enum() *EAttrType {
	p := new(EAttrType)
	*p = x
	return p
}

func (x EAttrType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EAttrType) Descriptor() protoreflect.EnumDescriptor {
	return file_pet_proto_enumTypes[0].Descriptor()
}

func (EAttrType) Type() protoreflect.EnumType {
	return &file_pet_proto_enumTypes[0]
}

func (x EAttrType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EAttrType.Descriptor instead.
func (EAttrType) EnumDescriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{0}
}

// 天赋等级是觉醒等级+1
type TalentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"talentId"
	TalentId uint32 `protobuf:"varint,1,opt,name=talentId,proto3" json:"talentId,omitempty"`
}

func (x *TalentInfo) Reset() {
	*x = TalentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalentInfo) ProtoMessage() {}

func (x *TalentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalentInfo.ProtoReflect.Descriptor instead.
func (*TalentInfo) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{0}
}

func (x *TalentInfo) GetTalentId() uint32 {
	if x != nil {
		return x.TalentId
	}
	return 0
}

type SkillInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"skillId"
	SkillId uint32 `protobuf:"varint,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	// @inject_tag: bson:"lvl"
	Lvl uint32 `protobuf:"varint,2,opt,name=lvl,proto3" json:"lvl,omitempty"`
	// @inject_tag: bson:"tempSkillId"
	TempSkillId uint32 `protobuf:"varint,3,opt,name=tempSkillId,proto3" json:"tempSkillId,omitempty"`
}

func (x *SkillInfo) Reset() {
	*x = SkillInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkillInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillInfo) ProtoMessage() {}

func (x *SkillInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillInfo.ProtoReflect.Descriptor instead.
func (*SkillInfo) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{1}
}

func (x *SkillInfo) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SkillInfo) GetLvl() uint32 {
	if x != nil {
		return x.Lvl
	}
	return 0
}

func (x *SkillInfo) GetTempSkillId() uint32 {
	if x != nil {
		return x.TempSkillId
	}
	return 0
}

type PetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"petUid"
	PetUid string `protobuf:"bytes,1,opt,name=petUid,proto3" json:"petUid,omitempty"`
	// @inject_tag: bson:"globalItemId"
	GlobalItemId uint32 `protobuf:"varint,2,opt,name=globalItemId,proto3" json:"globalItemId,omitempty"` //! 全局id
	// @inject_tag: bson:"birthTime"
	BirthTime uint32 `protobuf:"varint,3,opt,name=birthTime,proto3" json:"birthTime,omitempty"` //! 生效时间
	// @inject_tag: bson:"name"
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// @inject_tag: bson:"exp"
	Exp uint32 `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"` //! 放大100倍
	// @inject_tag: bson:"awakeLevel"
	AwakeLevel uint32 `protobuf:"varint,6,opt,name=awakeLevel,proto3" json:"awakeLevel,omitempty"` //! 觉醒等级跟突破是强关联的, 突破后觉醒等级才会提升
	// @inject_tag: bson:"attrList"
	AttrList []uint32 `protobuf:"varint,7,rep,packed,name=attrList,proto3" json:"attrList,omitempty"`
	// @inject_tag: bson:"talentList"
	TalentList []*TalentInfo `protobuf:"bytes,8,rep,name=talentList,proto3" json:"talentList,omitempty"`
	// @inject_tag: bson:"skillList"
	SkillList []*SkillInfo `protobuf:"bytes,9,rep,name=skillList,proto3" json:"skillList,omitempty"`
	// @inject_tag: bson:"buildUid"
	BuildUid string `protobuf:"bytes,10,opt,name=buildUid,proto3" json:"buildUid,omitempty"` //! 依附的建唯一id
	// @inject_tag: bson:"buildGlobalItemId"
	BuildGlobalItemId uint32 `protobuf:"varint,11,opt,name=buildGlobalItemId,proto3" json:"buildGlobalItemId,omitempty"` //! 依附建筑的全局id
	// @inject_tag: bson:"dispatchPointId"
	DispatchPointId uint32 `protobuf:"varint,12,opt,name=dispatchPointId,proto3" json:"dispatchPointId,omitempty"` //! 派遣点id
}

func (x *PetInfo) Reset() {
	*x = PetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetInfo) ProtoMessage() {}

func (x *PetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetInfo.ProtoReflect.Descriptor instead.
func (*PetInfo) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{2}
}

func (x *PetInfo) GetPetUid() string {
	if x != nil {
		return x.PetUid
	}
	return ""
}

func (x *PetInfo) GetGlobalItemId() uint32 {
	if x != nil {
		return x.GlobalItemId
	}
	return 0
}

func (x *PetInfo) GetBirthTime() uint32 {
	if x != nil {
		return x.BirthTime
	}
	return 0
}

func (x *PetInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PetInfo) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PetInfo) GetAwakeLevel() uint32 {
	if x != nil {
		return x.AwakeLevel
	}
	return 0
}

func (x *PetInfo) GetAttrList() []uint32 {
	if x != nil {
		return x.AttrList
	}
	return nil
}

func (x *PetInfo) GetTalentList() []*TalentInfo {
	if x != nil {
		return x.TalentList
	}
	return nil
}

func (x *PetInfo) GetSkillList() []*SkillInfo {
	if x != nil {
		return x.SkillList
	}
	return nil
}

func (x *PetInfo) GetBuildUid() string {
	if x != nil {
		return x.BuildUid
	}
	return ""
}

func (x *PetInfo) GetBuildGlobalItemId() uint32 {
	if x != nil {
		return x.BuildGlobalItemId
	}
	return 0
}

func (x *PetInfo) GetDispatchPointId() uint32 {
	if x != nil {
		return x.DispatchPointId
	}
	return 0
}

type Pet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @inject_tag: bson:"petList"
	PetList []*PetInfo `protobuf:"bytes,2,rep,name=petList,proto3" json:"petList,omitempty"`
	// @inject_tag: bson:"seq"
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *Pet) Reset() {
	*x = Pet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{3}
}

func (x *Pet) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Pet) GetPetList() []*PetInfo {
	if x != nil {
		return x.PetList
	}
	return nil
}

func (x *Pet) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_pet_proto protoreflect.FileDescriptor

var file_pet_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x22, 0x28, 0x0a, 0x0a, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x09,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x76, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6c, 0x76, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x9c, 0x03, 0x0a, 0x07, 0x50, 0x65, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x74, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x74, 0x55, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x65, 0x78, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x77, 0x61, 0x6b, 0x65, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x77, 0x61, 0x6b, 0x65, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x74, 0x74, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x31, 0x0a, 0x0a, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x61, 0x6c, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x12, 0x2c,
	0x0a, 0x11, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f,
	0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x03, 0x50, 0x65, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x28, 0x0a, 0x07, 0x70, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x07, 0x70, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x2a, 0x88, 0x01, 0x0a, 0x09,
	0x45, 0x41, 0x74, 0x74, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x41, 0x56,
	0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x41,
	0x56, 0x5f, 0x53, 0x4f, 0x43, 0x49, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x41,
	0x56, 0x5f, 0x42, 0x52, 0x45, 0x41, 0x44, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x41, 0x56,
	0x5f, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x41,
	0x56, 0x5f, 0x4c, 0x55, 0x43, 0x4b, 0x59, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x41, 0x56,
	0x5f, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x41, 0x56, 0x5f,
	0x45, 0x58, 0x50, 0x4c, 0x4f, 0x52, 0x45, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x41, 0x56,
	0x5f, 0x4d, 0x41, 0x58, 0x10, 0x07, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pet_proto_rawDescOnce sync.Once
	file_pet_proto_rawDescData = file_pet_proto_rawDesc
)

func file_pet_proto_rawDescGZIP() []byte {
	file_pet_proto_rawDescOnce.Do(func() {
		file_pet_proto_rawDescData = protoimpl.X.CompressGZIP(file_pet_proto_rawDescData)
	})
	return file_pet_proto_rawDescData
}

var file_pet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pet_proto_goTypes = []interface{}{
	(EAttrType)(0),     // 0: model.EAttrType
	(*TalentInfo)(nil), // 1: model.TalentInfo
	(*SkillInfo)(nil),  // 2: model.SkillInfo
	(*PetInfo)(nil),    // 3: model.PetInfo
	(*Pet)(nil),        // 4: model.Pet
}
var file_pet_proto_depIdxs = []int32{
	1, // 0: model.PetInfo.talentList:type_name -> model.TalentInfo
	2, // 1: model.PetInfo.skillList:type_name -> model.SkillInfo
	3, // 2: model.Pet.petList:type_name -> model.PetInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pet_proto_init() }
func file_pet_proto_init() {
	if File_pet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkillInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pet_proto_goTypes,
		DependencyIndexes: file_pet_proto_depIdxs,
		EnumInfos:         file_pet_proto_enumTypes,
		MessageInfos:      file_pet_proto_msgTypes,
	}.Build()
	File_pet_proto = out.File
	file_pet_proto_rawDesc = nil
	file_pet_proto_goTypes = nil
	file_pet_proto_depIdxs = nil
}
