// protoc --proto_path=./pb --go_out=./pbgo --go_opt=paths=source_relative ./pb/qqhallgift.proto
// protoc-go-inject-tag -input="./pbgo/qqhallgift.pb.go"
// goctl model mongo -e -dir ./model -t QQHallGift --home template -c
// qq大厅礼包相关

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: qqhallgift.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EQQHallGiftType int32

const (
	EQQHallGiftType_EQQHGT_Invalid EQQHallGiftType = 0
	EQQHallGiftType_EQQHGT_Daily   EQQHallGiftType = 1 // 每日礼包
	EQQHallGiftType_EQQHGT_Novices EQQHallGiftType = 2 // 新手礼包
	EQQHallGiftType_EQQHGT_Growth  EQQHallGiftType = 3 // 成长礼包
)

// Enum value maps for EQQHallGiftType.
var (
	EQQHallGiftType_name = map[int32]string{
		0: "EQQHGT_Invalid",
		1: "EQQHGT_Daily",
		2: "EQQHGT_Novices",
		3: "EQQHGT_Growth",
	}
	EQQHallGiftType_value = map[string]int32{
		"EQQHGT_Invalid": 0,
		"EQQHGT_Daily":   1,
		"EQQHGT_Novices": 2,
		"EQQHGT_Growth":  3,
	}
)

func (x EQQHallGiftType) Enum() *EQQHallGiftType {
	p := new(EQQHallGiftType)
	*p = x
	return p
}

func (x EQQHallGiftType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EQQHallGiftType) Descriptor() protoreflect.EnumDescriptor {
	return file_qqhallgift_proto_enumTypes[0].Descriptor()
}

func (EQQHallGiftType) Type() protoreflect.EnumType {
	return &file_qqhallgift_proto_enumTypes[0]
}

func (x EQQHallGiftType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EQQHallGiftType.Descriptor instead.
func (EQQHallGiftType) EnumDescriptor() ([]byte, []int) {
	return file_qqhallgift_proto_rawDescGZIP(), []int{0}
}

type QQHallGift struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @inject_tag: bson:"rewardTimes"
	RewardTimes []uint32 `protobuf:"varint,2,rep,packed,name=rewardTimes,proto3" json:"rewardTimes,omitempty"`
	// @inject_tag: bson:"seq"
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *QQHallGift) Reset() {
	*x = QQHallGift{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qqhallgift_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QQHallGift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QQHallGift) ProtoMessage() {}

func (x *QQHallGift) ProtoReflect() protoreflect.Message {
	mi := &file_qqhallgift_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QQHallGift.ProtoReflect.Descriptor instead.
func (*QQHallGift) Descriptor() ([]byte, []int) {
	return file_qqhallgift_proto_rawDescGZIP(), []int{0}
}

func (x *QQHallGift) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *QQHallGift) GetRewardTimes() []uint32 {
	if x != nil {
		return x.RewardTimes
	}
	return nil
}

func (x *QQHallGift) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_qqhallgift_proto protoreflect.FileDescriptor

var file_qqhallgift_proto_rawDesc = []byte{
	0x0a, 0x10, 0x71, 0x71, 0x68, 0x61, 0x6c, 0x6c, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x52, 0x0a, 0x0a, 0x51, 0x51, 0x48,
	0x61, 0x6c, 0x6c, 0x47, 0x69, 0x66, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x2a, 0x5e, 0x0a,
	0x0f, 0x45, 0x51, 0x51, 0x48, 0x61, 0x6c, 0x6c, 0x47, 0x69, 0x66, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x0e, 0x45, 0x51, 0x51, 0x48, 0x47, 0x54, 0x5f, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x51, 0x51, 0x48, 0x47, 0x54, 0x5f, 0x44,
	0x61, 0x69, 0x6c, 0x79, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x51, 0x51, 0x48, 0x47, 0x54,
	0x5f, 0x4e, 0x6f, 0x76, 0x69, 0x63, 0x65, 0x73, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x51,
	0x51, 0x48, 0x47, 0x54, 0x5f, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x10, 0x03, 0x42, 0x0d, 0x5a,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qqhallgift_proto_rawDescOnce sync.Once
	file_qqhallgift_proto_rawDescData = file_qqhallgift_proto_rawDesc
)

func file_qqhallgift_proto_rawDescGZIP() []byte {
	file_qqhallgift_proto_rawDescOnce.Do(func() {
		file_qqhallgift_proto_rawDescData = protoimpl.X.CompressGZIP(file_qqhallgift_proto_rawDescData)
	})
	return file_qqhallgift_proto_rawDescData
}

var file_qqhallgift_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_qqhallgift_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_qqhallgift_proto_goTypes = []interface{}{
	(EQQHallGiftType)(0), // 0: model.EQQHallGiftType
	(*QQHallGift)(nil),   // 1: model.QQHallGift
}
var file_qqhallgift_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qqhallgift_proto_init() }
func file_qqhallgift_proto_init() {
	if File_qqhallgift_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qqhallgift_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QQHallGift); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qqhallgift_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qqhallgift_proto_goTypes,
		DependencyIndexes: file_qqhallgift_proto_depIdxs,
		EnumInfos:         file_qqhallgift_proto_enumTypes,
		MessageInfos:      file_qqhallgift_proto_msgTypes,
	}.Build()
	File_qqhallgift_proto = out.File
	file_qqhallgift_proto_rawDesc = nil
	file_qqhallgift_proto_goTypes = nil
	file_qqhallgift_proto_depIdxs = nil
}
