// goctl model mongo -e -dir ./model -t smallGames --home template -c

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: smallGames.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmallGameID int32

const (
	SmallGameID_SGID_INVALID SmallGameID = 0
	SmallGameID_SGID_LLK     SmallGameID = 1 //连连看
	SmallGameID_SGID_TETRIS  SmallGameID = 2 //俄罗斯方块
)

// Enum value maps for SmallGameID.
var (
	SmallGameID_name = map[int32]string{
		0: "SGID_INVALID",
		1: "SGID_LLK",
		2: "SGID_TETRIS",
	}
	SmallGameID_value = map[string]int32{
		"SGID_INVALID": 0,
		"SGID_LLK":     1,
		"SGID_TETRIS":  2,
	}
)

func (x SmallGameID) Enum() *SmallGameID {
	p := new(SmallGameID)
	*p = x
	return p
}

func (x SmallGameID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmallGameID) Descriptor() protoreflect.EnumDescriptor {
	return file_smallGames_proto_enumTypes[0].Descriptor()
}

func (SmallGameID) Type() protoreflect.EnumType {
	return &file_smallGames_proto_enumTypes[0]
}

func (x SmallGameID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmallGameID.Descriptor instead.
func (SmallGameID) EnumDescriptor() ([]byte, []int) {
	return file_smallGames_proto_rawDescGZIP(), []int{0}
}

type SmallGameStatus int32

const (
	SmallGameStatus_SGS_NULL     SmallGameStatus = 0
	SmallGameStatus_SGS_MATCHING SmallGameStatus = 1 //匹配中
	SmallGameStatus_SGS_GAMING   SmallGameStatus = 2 //游戏中
	SmallGameStatus_SGS_END      SmallGameStatus = 3 //结束
)

// Enum value maps for SmallGameStatus.
var (
	SmallGameStatus_name = map[int32]string{
		0: "SGS_NULL",
		1: "SGS_MATCHING",
		2: "SGS_GAMING",
		3: "SGS_END",
	}
	SmallGameStatus_value = map[string]int32{
		"SGS_NULL":     0,
		"SGS_MATCHING": 1,
		"SGS_GAMING":   2,
		"SGS_END":      3,
	}
)

func (x SmallGameStatus) Enum() *SmallGameStatus {
	p := new(SmallGameStatus)
	*p = x
	return p
}

func (x SmallGameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmallGameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_smallGames_proto_enumTypes[1].Descriptor()
}

func (SmallGameStatus) Type() protoreflect.EnumType {
	return &file_smallGames_proto_enumTypes[1]
}

func (x SmallGameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmallGameStatus.Descriptor instead.
func (SmallGameStatus) EnumDescriptor() ([]byte, []int) {
	return file_smallGames_proto_rawDescGZIP(), []int{1}
}

type SmallGames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @inject_tag: bson:"seq"
	Seq uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// @inject_tag: bson:"gameID"
	GameID SmallGameID `protobuf:"varint,3,opt,name=gameID,proto3,enum=model.SmallGameID" json:"gameID,omitempty"`
	// @inject_tag: bson:"status"
	Status SmallGameStatus `protobuf:"varint,4,opt,name=status,proto3,enum=model.SmallGameStatus" json:"status,omitempty"` //游戏状态
	// @inject_tag: bson:"ts"
	Ts int64 `protobuf:"varint,5,opt,name=ts,proto3" json:"ts,omitempty"` //更新时间戳
}

func (x *SmallGames) Reset() {
	*x = SmallGames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smallGames_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmallGames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmallGames) ProtoMessage() {}

func (x *SmallGames) ProtoReflect() protoreflect.Message {
	mi := &file_smallGames_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmallGames.ProtoReflect.Descriptor instead.
func (*SmallGames) Descriptor() ([]byte, []int) {
	return file_smallGames_proto_rawDescGZIP(), []int{0}
}

func (x *SmallGames) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *SmallGames) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SmallGames) GetGameID() SmallGameID {
	if x != nil {
		return x.GameID
	}
	return SmallGameID_SGID_INVALID
}

func (x *SmallGames) GetStatus() SmallGameStatus {
	if x != nil {
		return x.Status
	}
	return SmallGameStatus_SGS_NULL
}

func (x *SmallGames) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

var File_smallGames_proto protoreflect.FileDescriptor

var file_smallGames_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x9c, 0x01, 0x0a, 0x0a, 0x53, 0x6d,
	0x61, 0x6c, 0x6c, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44,
	0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x2a, 0x3e, 0x0a, 0x0b, 0x53, 0x6d, 0x61, 0x6c,
	0x6c, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x47, 0x49, 0x44, 0x5f,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x47, 0x49,
	0x44, 0x5f, 0x4c, 0x4c, 0x4b, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x47, 0x49, 0x44, 0x5f,
	0x54, 0x45, 0x54, 0x52, 0x49, 0x53, 0x10, 0x02, 0x2a, 0x4e, 0x0a, 0x0f, 0x53, 0x6d, 0x61, 0x6c,
	0x6c, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x53,
	0x47, 0x53, 0x5f, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x47, 0x53,
	0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x53,
	0x47, 0x53, 0x5f, 0x47, 0x41, 0x4d, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x47, 0x53, 0x5f, 0x45, 0x4e, 0x44, 0x10, 0x03, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smallGames_proto_rawDescOnce sync.Once
	file_smallGames_proto_rawDescData = file_smallGames_proto_rawDesc
)

func file_smallGames_proto_rawDescGZIP() []byte {
	file_smallGames_proto_rawDescOnce.Do(func() {
		file_smallGames_proto_rawDescData = protoimpl.X.CompressGZIP(file_smallGames_proto_rawDescData)
	})
	return file_smallGames_proto_rawDescData
}

var file_smallGames_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_smallGames_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_smallGames_proto_goTypes = []interface{}{
	(SmallGameID)(0),     // 0: model.SmallGameID
	(SmallGameStatus)(0), // 1: model.SmallGameStatus
	(*SmallGames)(nil),   // 2: model.SmallGames
}
var file_smallGames_proto_depIdxs = []int32{
	0, // 0: model.SmallGames.gameID:type_name -> model.SmallGameID
	1, // 1: model.SmallGames.status:type_name -> model.SmallGameStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_smallGames_proto_init() }
func file_smallGames_proto_init() {
	if File_smallGames_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smallGames_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmallGames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smallGames_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smallGames_proto_goTypes,
		DependencyIndexes: file_smallGames_proto_depIdxs,
		EnumInfos:         file_smallGames_proto_enumTypes,
		MessageInfos:      file_smallGames_proto_msgTypes,
	}.Build()
	File_smallGames_proto = out.File
	file_smallGames_proto_rawDesc = nil
	file_smallGames_proto_goTypes = nil
	file_smallGames_proto_depIdxs = nil
}
