// protoc --proto_path=./pb --go_out=./pbgo --go_opt=paths=source_relative ./pb/taskActivity.proto
// protoc-go-inject-tag -input="./pbgo/taskActivity.pb.go"
// goctl model mongo -e -dir ./model -t TaskActivity --home template -c

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: taskActivity.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskActivityCondData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"needEventId"
	NeedEventId ETaskEventId `protobuf:"varint,1,opt,name=needEventId,proto3,enum=model.ETaskEventId" json:"needEventId,omitempty"`
	// @inject_tag: bson:"needPropList"
	NeedPropList []*BaseItemInfo `protobuf:"bytes,2,rep,name=needPropList,proto3" json:"needPropList,omitempty"`
}

func (x *TaskActivityCondData) Reset() {
	*x = TaskActivityCondData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskActivity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskActivityCondData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskActivityCondData) ProtoMessage() {}

func (x *TaskActivityCondData) ProtoReflect() protoreflect.Message {
	mi := &file_taskActivity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskActivityCondData.ProtoReflect.Descriptor instead.
func (*TaskActivityCondData) Descriptor() ([]byte, []int) {
	return file_taskActivity_proto_rawDescGZIP(), []int{0}
}

func (x *TaskActivityCondData) GetNeedEventId() ETaskEventId {
	if x != nil {
		return x.NeedEventId
	}
	return ETaskEventId_ETEI_Invalid
}

func (x *TaskActivityCondData) GetNeedPropList() []*BaseItemInfo {
	if x != nil {
		return x.NeedPropList
	}
	return nil
}

type TaskActivityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"activityId"
	ActivityId string `protobuf:"bytes,1,opt,name=activityId,proto3" json:"activityId,omitempty"`
	// @inject_tag: bson:"taskId"
	TaskId uint32 `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	// @inject_tag: bson:"createAt"
	CreateAt uint32 `protobuf:"varint,3,opt,name=createAt,proto3" json:"createAt,omitempty"` //! 创建时间
	// @inject_tag: bson:"updateAt"
	UpdateAt uint32 `protobuf:"varint,4,opt,name=updateAt,proto3" json:"updateAt,omitempty"` //! 更新时间
	// @inject_tag: bson:"taskCondData"
	TaskCondData *TaskActivityCondData `protobuf:"bytes,5,opt,name=taskCondData,proto3" json:"taskCondData,omitempty"` //! 完成条件的数据
	// @inject_tag: bson:"taskStatus"
	TaskStatus ETaskStatus `protobuf:"varint,6,opt,name=taskStatus,proto3,enum=model.ETaskStatus" json:"taskStatus,omitempty"`
}

func (x *TaskActivityInfo) Reset() {
	*x = TaskActivityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskActivity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskActivityInfo) ProtoMessage() {}

func (x *TaskActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_taskActivity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskActivityInfo.ProtoReflect.Descriptor instead.
func (*TaskActivityInfo) Descriptor() ([]byte, []int) {
	return file_taskActivity_proto_rawDescGZIP(), []int{1}
}

func (x *TaskActivityInfo) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *TaskActivityInfo) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskActivityInfo) GetCreateAt() uint32 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *TaskActivityInfo) GetUpdateAt() uint32 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

func (x *TaskActivityInfo) GetTaskCondData() *TaskActivityCondData {
	if x != nil {
		return x.TaskCondData
	}
	return nil
}

func (x *TaskActivityInfo) GetTaskStatus() ETaskStatus {
	if x != nil {
		return x.TaskStatus
	}
	return ETaskStatus_ETS_Invalid
}

type TaskActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// index为uid和taskId，唯一id系统生成
	// @inject_tag: bson:"uid"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @inject_tag: bson:"taskActivityInfoList"
	TaskActivityInfoList []*TaskActivityInfo `protobuf:"bytes,2,rep,name=taskActivityInfoList,proto3" json:"taskActivityInfoList,omitempty"`
	// @inject_tag: bson:"seq"
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *TaskActivity) Reset() {
	*x = TaskActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskActivity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskActivity) ProtoMessage() {}

func (x *TaskActivity) ProtoReflect() protoreflect.Message {
	mi := &file_taskActivity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskActivity.ProtoReflect.Descriptor instead.
func (*TaskActivity) Descriptor() ([]byte, []int) {
	return file_taskActivity_proto_rawDescGZIP(), []int{2}
}

func (x *TaskActivity) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *TaskActivity) GetTaskActivityInfoList() []*TaskActivityInfo {
	if x != nil {
		return x.TaskActivityInfoList
	}
	return nil
}

func (x *TaskActivity) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_taskActivity_proto protoreflect.FileDescriptor

var file_taskActivity_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x14, 0x54, 0x61,
	0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x35, 0x0a, 0x0b, 0x6e, 0x65, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x45, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x0b, 0x6e, 0x65,
	0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x6e, 0x65, 0x65,
	0x64, 0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x6e, 0x65, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0xf7, 0x01, 0x0a, 0x10, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x3f, 0x0a, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x43,
	0x6f, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x43, 0x6f, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x74, 0x61, 0x73, 0x6b,
	0x43, 0x6f, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x0a, 0x74, 0x61, 0x73, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x7f, 0x0a, 0x0c,
	0x54, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x4b,
	0x0a, 0x14, 0x74, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x14, 0x74, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x42, 0x0d, 0x5a,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_taskActivity_proto_rawDescOnce sync.Once
	file_taskActivity_proto_rawDescData = file_taskActivity_proto_rawDesc
)

func file_taskActivity_proto_rawDescGZIP() []byte {
	file_taskActivity_proto_rawDescOnce.Do(func() {
		file_taskActivity_proto_rawDescData = protoimpl.X.CompressGZIP(file_taskActivity_proto_rawDescData)
	})
	return file_taskActivity_proto_rawDescData
}

var file_taskActivity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_taskActivity_proto_goTypes = []interface{}{
	(*TaskActivityCondData)(nil), // 0: model.TaskActivityCondData
	(*TaskActivityInfo)(nil),     // 1: model.TaskActivityInfo
	(*TaskActivity)(nil),         // 2: model.TaskActivity
	(ETaskEventId)(0),            // 3: model.ETaskEventId
	(*BaseItemInfo)(nil),         // 4: model.BaseItemInfo
	(ETaskStatus)(0),             // 5: model.ETaskStatus
}
var file_taskActivity_proto_depIdxs = []int32{
	3, // 0: model.TaskActivityCondData.needEventId:type_name -> model.ETaskEventId
	4, // 1: model.TaskActivityCondData.needPropList:type_name -> model.BaseItemInfo
	0, // 2: model.TaskActivityInfo.taskCondData:type_name -> model.TaskActivityCondData
	5, // 3: model.TaskActivityInfo.taskStatus:type_name -> model.ETaskStatus
	1, // 4: model.TaskActivity.taskActivityInfoList:type_name -> model.TaskActivityInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_taskActivity_proto_init() }
func file_taskActivity_proto_init() {
	if File_taskActivity_proto != nil {
		return
	}
	file_common_proto_init()
	file_itemInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_taskActivity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskActivityCondData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskActivity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskActivityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskActivity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_taskActivity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taskActivity_proto_goTypes,
		DependencyIndexes: file_taskActivity_proto_depIdxs,
		MessageInfos:      file_taskActivity_proto_msgTypes,
	}.Build()
	File_taskActivity_proto = out.File
	file_taskActivity_proto_rawDesc = nil
	file_taskActivity_proto_goTypes = nil
	file_taskActivity_proto_depIdxs = nil
}
